apiVersion: v1
kind: ServiceAccount
metadata:
  name: buoyant-operator-migration
  namespace: linkerd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: buoyant-operator-migration
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: buoyant-operator-migration
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: buoyant-operator-migration
subjects:
- kind: ServiceAccount
  name: buoyant-operator-migration
  namespace: linkerd