kind: Secret
apiVersion: v1
metadata:
  name: buoyant-cloud-org-credentials
  namespace: linkerd-buoyant
  labels:
    app.kubernetes.io/part-of: linkerd-buoyant
type: Opaque
data:
  client_id: $CLIENT_ID
  client_secret: $CLIENT_SECRET
