apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-buoyant
  namespace: argocd
  labels:
    type: child
spec:
  project: linkerd
  sources:
    - repoURL: https://helm.buoyant.cloud
      chart: linkerd-buoyant
      targetRevision: 0.26.1
      helm:
        valueFiles:
        - $values/examples/argocd/bcloud/bel/linkerd-buoyant/values.yaml
    - repoURL: 'git@github.com:deusxanima/linkerd_cx.git'
      targetRevision: HEAD
      ref: values
  destination:
    namespace: linkerd-buoyant
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true